# Generated by Django 3.2.3 on 2021-06-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_mytodo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytodo',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='mytodo',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified'),
        ),
    ]
