# Generated by Django 3.2.3 on 2021-06-06 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_auto_20210606_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytodo',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='mytodo',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Date Modified'),
        ),
    ]
