# Generated by Django 3.2.3 on 2021-06-06 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_auto_20210606_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytodo',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='mytodo',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Date Modified'),
        ),
    ]
